language: node_js
addons:
  firefox: "24.5.0esr"
node_js:
  - "0.10.30"
services:
  - mongodb
before_install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
  - export DISPLAY=:99.0
  - "sh -e /etc/init.d/xvfb start"
env: NODE_ENV=travis-ci MASSAH_BROWSER=phantomjs
